/* ============================================================
 *  金融知识终极架构 · 数据层（Wall Street Ultimate Knowledge Architecture v4.0）
 *  ------------------------------------------------------------
 *  8 层级 · 48 模块 · 560+ 中英双语术语
 *
 *  数据结构：
 *  ARCH.layers[] —— 8 个层级 (L1–L8)
 *    ├─ id      "L1"
 *    ├─ icon    emoji
 *    ├─ cn/en   层级中/英文名
 *    ├─ tag     层级定位（一句话）
 *    ├─ accent  主题色
 *    └─ modules[] —— 该层的模块
 *         ├─ id     "L1-M1"
 *         ├─ cn/en  模块中/英文名
 *         ├─ isNew  是否 v4.0 新增（★）
 *         └─ terms[] —— 术语，每条为 [中文名, English Name, 说明?]
 *
 *  新增/修改术语：编辑对应模块的 terms 数组即可，页面自动渲染与统计。
 * ============================================================ */

const ARCH = {
  meta: {
    title: "金融知识终极架构",
    en: "Wall Street · Ultimate Knowledge Architecture",
    version: "v4.0",
    date: "2026 年 3 月 · 第四版",
    intro:
      "本框架从数学基础出发，逐层构建至专业纵深与监管合规，覆盖华尔街从业者所需的完整知识体系——" +
      "前台 / 中台 / 后台、危机机制、认知元层与专业纵深无所不包。八个层级层层依赖：" +
      "L1 数理工具 → L2 市场机制 → L3 衍生品定价 → L4 组合与风险 → L5 另类与结构化 → " +
      "L6 宏观与行为 → L7 专业纵深 → L8 监管与合规。校验坐标：CFA × FRM × SOA 精算 × 顶级商学院 × " +
      "Bloomberg × ISDA/BIS/IOSCO × 投行培训 × Pozsar / Mehrling / Brunnermeier / Gatheral 学术与实务。",
  },

  layers: [
    /* ============== L1 ============== */
    {
      id: "L1", icon: "🧮", cn: "数学工具层", en: "Mathematical Foundations",
      tag: "金融工程的数学根基——从线性代数到随机微积分，涵盖定价与风控所需的全部数学工具。",
      accent: "#8aa6ff",
      modules: [
        { id: "L1-M1", cn: "核心数学运算", en: "Core Mathematical Operations", isNew: false, terms: [
          ["矩阵分解", "Matrix Decomposition", "将矩阵分解为更简单矩阵的乘积"],
          ["特征值分解", "Eigenvalue Decomposition", "把方阵分解为特征值与特征向量，揭示线性变换的主轴"],
          ["奇异值分解", "Singular Value Decomposition (SVD)", "任意矩阵分解为 UΣVᵀ，用于降维、PCA 与低秩逼近"],
          ["Cholesky 分解", "Cholesky Decomposition", "正定矩阵的下三角分解"],
          ["QR 分解", "QR Decomposition", "矩阵分解为正交阵 Q 与上三角阵 R，常用于最小二乘"],
          ["张量运算", "Tensor Operations", "高维数组（张量）的运算，深度学习与多因子建模的基础"],
          ["稀疏矩阵计算", "Sparse Matrix Computation", "针对大量零元素矩阵的高效存储与运算"],
          ["数值积分方法", "Numerical Integration Methods", "用数值方法近似定积分（梯形、辛普森法等）"],
          ["有限差分法", "Finite Difference Method (FDM)", "用差分近似导数求解偏微分方程，常用于期权定价"],
          ["有限元分析", "Finite Element Analysis (FEA)", "将区域离散为单元求解微分方程的数值方法"],
        ]},
        { id: "L1-M2", cn: "概率与统计推断", en: "Probability & Statistical Inference", isNew: false, terms: [
          ["贝叶斯推断", "Bayesian Inference", "用先验加似然更新为后验概率的推断框架"],
          ["极大似然估计", "Maximum Likelihood Estimation (MLE)", "选使样本似然最大的参数估计法"],
          ["广义矩估计", "Generalized Method of Moments (GMM)", "用样本矩条件估计参数，计量经济学核心方法"],
          ["核密度估计", "Kernel Density Estimation (KDE)", "用核函数平滑估计概率密度的非参数方法"],
          ["Copula 函数", "Copula Functions", "联合分布建模"],
          ["极值理论", "Extreme Value Theory (EVT)", "研究极端尾部事件分布，用于极端风险度量"],
          ["混合分布模型", "Mixture Distribution Models", "用多个分布加权刻画多峰或异质数据"],
          ["Bootstrap 方法", "Bootstrap Methods", "通过有放回重抽样估计统计量的分布与置信区间"],
          ["马尔可夫链蒙特卡洛", "Markov Chain Monte Carlo (MCMC)", "用马氏链从复杂后验分布中抽样的方法"],
          ["充分统计量", "Sufficient Statistics", "概括样本中关于参数全部信息的统计量"],
          ["Delta 方法", "Delta Method", "用一阶泰勒展开近似函数估计量的渐近方差"],
          ["似然比检验", "Likelihood Ratio Test", "用似然比比较嵌套模型的假设检验"],
        ]},
        { id: "L1-M3", cn: "随机过程", en: "Stochastic Processes", isNew: false, terms: [
          ["布朗运动", "Brownian Motion", "连续时间随机过程基础"],
          ["几何布朗运动", "Geometric Brownian Motion (GBM)", "价格恒为正的对数正态随机过程，BS 模型的假设"],
          ["泊松过程", "Poisson Process", "刻画随机到达或跳跃次数的计数过程"],
          ["跳扩散过程", "Jump-Diffusion Process", "Merton 模型"],
          ["Ornstein-Uhlenbeck 过程", "Ornstein-Uhlenbeck Process", "均值回复过程"],
          ["Lévy 过程", "Lévy Process", "具有独立平稳增量、可含跳跃的一般化过程"],
          ["分数布朗运动", "Fractional Brownian Motion", "带长程相关性的布朗运动推广"],
          ["鞅理论", "Martingale Theory", "无套利定价的数学基础，条件期望不随时间漂移"],
          ["停时理论", "Stopping Time Theory", "研究最优停止时刻，如美式期权的行权决策"],
          ["Girsanov 定理", "Girsanov's Theorem", "测度变换"],
          ["Itô 引理", "Itô's Lemma", "随机微积分核心"],
          ["Feynman-Kac 公式", "Feynman-Kac Formula", "把偏微分方程解表示为随机过程期望的桥梁"],
          ["随机微分方程", "Stochastic Differential Equations (SDE)", "含随机项的微分方程，资产价格建模的基础"],
          ["CIR 过程", "Cox-Ingersoll-Ross Process", "利率建模"],
          ["Heston 随机波动率", "Heston Stochastic Volatility", "波动率本身随机波动的期权定价模型"],
        ]},
        { id: "L1-M4", cn: "优化理论", en: "Optimization Theory", isNew: false, terms: [
          ["凸优化", "Convex Optimization", "凸目标加凸约束的优化，保证全局最优且可高效求解"],
          ["二次规划", "Quadratic Programming (QP)", "二次目标加线性约束的优化，均值-方差组合的解法"],
          ["线性规划", "Linear Programming (LP)", "线性目标加线性约束的优化问题"],
          ["动态规划", "Dynamic Programming", "Bellman 方程"],
          ["随机优化", "Stochastic Optimization", "目标含随机性的优化，如随机梯度下降"],
          ["遗传算法", "Genetic Algorithm", "模拟自然选择与遗传的启发式全局优化"],
          ["粒子群优化", "Particle Swarm Optimization", "模拟群体协作寻优的启发式算法"],
          ["拉格朗日乘子法", "Lagrange Multiplier Method", "用乘子把约束优化转化为无约束问题"],
          ["KKT 条件", "Karush-Kuhn-Tucker Conditions", "含不等式约束优化的最优性（KKT）条件"],
          ["梯度下降法", "Gradient Descent", "沿负梯度迭代求极小值的基础优化法"],
          ["牛顿法", "Newton's Method", "利用二阶信息加速收敛的迭代求解法"],
          ["模拟退火", "Simulated Annealing", "借鉴退火、以概率跳出局部最优的算法"],
        ]},
        { id: "L1-M5", cn: "时间序列分析", en: "Time Series Analysis", isNew: false, terms: [
          ["自回归模型", "Autoregressive Model (AR)", "用自身历史值预测当前值的时间序列模型"],
          ["移动平均模型", "Moving Average Model (MA)", "用历史误差项建模的时间序列模型"],
          ["ARIMA 模型", "ARIMA Model", "差分加 AR 加 MA 的经典时间序列预测模型"],
          ["GARCH 模型", "Generalized Autoregressive Conditional Heteroskedasticity", "刻画波动率聚集与时变方差的 GARCH 模型"],
          ["EGARCH", "Exponential GARCH", "允许波动率对涨跌不对称反应的 GARCH 变体"],
          ["协整检验", "Cointegration Test", "Engle-Granger / Johansen"],
          ["向量自回归", "Vector Autoregression (VAR)", "多变量相互滞后影响的联合时间序列模型"],
          ["状态空间模型", "State Space Model", "用隐含状态加观测方程描述动态系统"],
          ["卡尔曼滤波", "Kalman Filter", "从含噪观测递归估计隐含状态的滤波器"],
          ["谱分析", "Spectral Analysis", "从频域分析时间序列的周期成分"],
          ["小波变换", "Wavelet Transform", "同时在时域与频域分解信号的方法"],
          ["体制转换模型", "Regime Switching Model", "Hamilton"],
        ]},
        { id: "L1-M6", cn: "机器学习与 AI 方法", en: "Machine Learning & AI Methods", isNew: false, terms: [
          ["随机森林", "Random Forest", "多棵决策树集成、降低过拟合的机器学习模型"],
          ["梯度提升机", "Gradient Boosting Machine (XGBoost/LightGBM)", "逐步拟合残差的提升树，量化选股常用"],
          ["支持向量机", "Support Vector Machine (SVM)", "寻找最大间隔超平面的分类与回归模型"],
          ["深度学习", "Deep Learning", "CNN / RNN / Transformer"],
          ["长短期记忆网络", "Long Short-Term Memory (LSTM)", "擅长长序列依赖的循环神经网络"],
          ["注意力机制", "Attention Mechanism", "让模型聚焦关键输入的机制，Transformer 的核心"],
          ["生成对抗网络", "Generative Adversarial Network (GAN)", "生成器与判别器对抗训练来生成数据"],
          ["变分自编码器", "Variational Autoencoder (VAE)", "学习隐分布并生成数据的概率自编码器"],
          ["强化学习", "Reinforcement Learning", "做市与执行优化"],
          ["自然语言处理", "Natural Language Processing (NLP)", "让机器理解与处理文本，用于舆情与研报分析"],
          ["图神经网络", "Graph Neural Network (GNN)", "在图结构上学习的神经网络，用于关系网络"],
          ["迁移学习", "Transfer Learning", "把已训练模型迁移到新任务以省数据的方法"],
        ]},
        { id: "L1-M7", cn: "因果推断与网络科学", en: "Causal Inference & Network Science", isNew: true, terms: [
          ["因果推断框架", "Causal Inference Framework", "Pearl's Do-Calculus"],
          ["工具变量法", "Instrumental Variables (IV)", "用工具变量处理内生性、识别因果"],
          ["双重差分法", "Difference-in-Differences (DiD)", "用处理组与对照组差分识别政策效应"],
          ["倾向得分匹配", "Propensity Score Matching", "按倾向得分配对以估计处理效应"],
          ["断点回归", "Regression Discontinuity Design (RDD)", "利用阈值断点识别因果的准实验方法"],
          ["合成控制法", "Synthetic Control Method", "用加权组合构造反事实对照组"],
          ["图论基础", "Graph Theory Foundations", "研究节点与边关系的数学基础，网络分析的根基"],
          ["网络中心性", "Network Centrality Measures", "系统性风险传染建模"],
          ["社区检测", "Community Detection", "金融网络聚类"],
          ["传染模型", "Contagion Models", "级联违约建模"],
          ["多层网络", "Multilayer Networks", "跨市场关联结构"],
        ]},
      ],
    },

    /* ============== L2 ============== */
    {
      id: "L2", icon: "📊", cn: "市场微观结构", en: "Market Microstructure",
      tag: "从订单簿到暗池——理解价格如何形成、流动性如何流转、交易如何执行与清算。",
      accent: "#6fe0c4",
      modules: [
        { id: "L2-M1", cn: "价格发现机制", en: "Price Discovery Mechanism", isNew: false, terms: [
          ["限价订单簿", "Limit Order Book (LOB)", "按价格档位排列所有限价买卖单的电子簿"],
          ["做市商机制", "Market Maker Mechanism", "做市商双边报价提供流动性、赚取买卖价差"],
          ["买卖价差", "Bid-Ask Spread", "买价与卖价之差，流动性成本的核心度量"],
          ["有效价差", "Effective Spread", "按实际成交价衡量的真实交易成本"],
          ["实现价差", "Realized Spread", "剔除价格冲击后做市商实得的价差"],
          ["信息份额", "Information Share", "Hasbrouck 模型"],
          ["成分份额", "Component Share", "Gonzalo-Granger"],
          ["价格冲击", "Price Impact", "Kyle Lambda"],
          ["Amihud 非流动性比率", "Amihud Illiquidity Ratio", "用单位成交额引起的价格变动衡量非流动性"],
          ["Roll 价差估计", "Roll Spread Estimator", "由价格自协方差反推有效价差的方法"],
          ["成交量加权均价", "Volume-Weighted Average Price (VWAP)", "按成交量加权的平均价，常用执行基准"],
          ["时间加权均价", "Time-Weighted Average Price (TWAP)", "按时间均匀加权的平均价，常用执行基准"],
        ]},
        { id: "L2-M2", cn: "订单流分析", en: "Order Flow Analysis", isNew: false, terms: [
          ["订单流毒性", "Order Flow Toxicity", "VPIN 模型"],
          ["信息不对称", "Information Asymmetry", "交易一方掌握更多信息造成的不对称"],
          ["逆向选择", "Adverse Selection", "Glosten-Milgrom"],
          ["知情交易概率", "Probability of Informed Trading (PIN)", "估计订单来自知情交易者的概率"],
          ["订单簿失衡", "Order Book Imbalance (OBI)", "买卖挂单量失衡，短期价格方向的信号"],
          ["瞬时波动率", "Instantaneous Volatility", "某一时刻的瞬时波动率水平"],
          ["逐笔数据分析", "Tick Data Analysis", "对逐笔成交与报价数据的微观分析"],
          ["Lee-Ready 算法", "Lee-Ready Algorithm", "交易方向判定"],
          ["订单流聚类", "Order Flow Clustering", "订单在时间上成簇到达的特征"],
          ["冰山订单检测", "Iceberg Order Detection", "识别只露一角的大额隐藏挂单"],
        ]},
        { id: "L2-M3", cn: "市场结构与交易场所", en: "Market Structure & Trading Venues", isNew: false, terms: [
          ["中央限价订单簿", "Central Limit Order Book (CLOB)", "集中撮合所有限价单的中央订单簿"],
          ["电子通信网络", "Electronic Communication Network (ECN)", "自动撮合买卖盘的电子交易网络"],
          ["另类交易系统", "Alternative Trading System (ATS)", "交易所之外的另类撮合平台，含暗池"],
          ["暗池", "Dark Pool", "信息泄露与价格发现"],
          ["暗池分层分类", "Dark Pool Taxonomy", "Midpoint / Conditional / Retail"],
          ["市场碎片化", "Market Fragmentation", "碎片化度量指标"],
          ["跨市场套利", "Cross-Market Arbitrage", "利用不同市场同一资产的价差套利"],
          ["最佳执行义务", "Best Execution Obligation", "券商须为客户争取最优成交的义务"],
          ["交易后透明度", "Post-Trade Transparency", "成交后价格与数量的公开披露"],
          ["单一交易商平台", "Single Dealer Platform (SDP)", "单一交易商自营报价的交易平台"],
          ["系统性内部化商", "Systematic Internaliser (SI)", "MiFID II 框架"],
        ]},
        { id: "L2-M4", cn: "高频交易与算法执行", en: "High-Frequency Trading & Algo Execution", isNew: false, terms: [
          ["高频做市", "HFT Market Making", "高频算法双边报价做市"],
          ["统计套利", "Statistical Arbitrage", "基于统计规律的多空对冲套利"],
          ["延迟套利", "Latency Arbitrage", "利用毫秒级速度优势抢先成交"],
          ["共置 / 托管", "Co-location / Proximity Hosting", "服务器托管于交易所机房以降低延迟"],
          ["FPGA 加速", "FPGA Acceleration", "用可编程硬件实现超低延迟交易"],
          ["智能订单路由", "Smart Order Routing (SOR)", "自动把订单拆分路由到最优场所"],
          ["执行算法", "Execution Algorithms", "IS / VWAP / TWAP / POV"],
          ["交易成本分析", "Transaction Cost Analysis (TCA)", "量化评估交易执行成本的分析"],
          ["滑点分析", "Slippage Analysis", "分析预期价与实际成交价的偏差"],
          ["实施差额", "Implementation Shortfall", "决策价与最终成交的总成本之差"],
          ["市场冲击模型", "Market Impact Model", "Almgren-Chriss"],
          ["最优执行", "Optimal Execution", "在冲击与风险间权衡的最优下单策略"],
        ]},
        { id: "L2-M5", cn: "结算与清算基础设施", en: "Clearing & Settlement Infrastructure", isNew: false, terms: [
          ["中央对手方清算", "Central Counterparty Clearing (CCP)", "中央对手方居间承担双方违约风险"],
          ["双边清算", "Bilateral Clearing", "交易双方直接结算、不经中央对手"],
          ["交割对付款", "Delivery vs Payment (DvP)", "券款同步交割，消除结算风险"],
          ["T+1 结算周期", "T+1 Settlement Cycle", "成交后次日完成交割的结算周期"],
          ["保证金体系", "Margin System", "初始 / 变动 / 维持保证金"],
          ["违约瀑布", "Default Waterfall", "CCP 应对违约的分层损失吸收顺序"],
          ["轧差结算", "Netting", "双边 / 多边轧差"],
          ["证券借贷", "Securities Lending", "出借证券收费，支持卖空与结算"],
          ["回购协议", "Repurchase Agreement (Repo)", "卖出证券并约定回购的抵押融资"],
          ["逆回购", "Reverse Repo", "买入证券并约定卖回，即资金融出方"],
          ["三方回购", "Tri-Party Repo", "由第三方托管管理抵押品的回购"],
        ]},
        { id: "L2-M6", cn: "加密市场微观结构", en: "Crypto Market Microstructure", isNew: true, terms: [
          ["自动做市商", "Automated Market Maker (AMM)", "Uniswap v3 集中流动性"],
          ["流动性池定价", "Liquidity Pool Pricing", "恒定乘积 / 恒定和"],
          ["最大可提取价值", "Maximal Extractable Value (MEV)", "打包区块时通过排序可提取的额外收益"],
          ["三明治攻击", "Sandwich Attack", "在目标交易前后夹单获利的攻击"],
          ["闪电贷", "Flash Loan", "同一笔交易内借还的无抵押贷款"],
          ["永续合约资金费率", "Perpetual Swap Funding Rate", "永续合约多空之间的周期性资金费"],
          ["链上订单簿", "On-Chain Order Book", "完全在区块链上撮合的订单簿"],
          ["预言机机制", "Oracle Mechanism", "Chainlink / TWAP"],
          ["跨链桥流动性", "Cross-Chain Bridge Liquidity", "跨链桥中支持资产互通的流动性"],
        ]},
      ],
    },

    /* ============== L3 ============== */
    {
      id: "L3", icon: "🎲", cn: "衍生品定价层", en: "Derivatives Pricing",
      tag: "从 Black-Scholes 到粗糙波动率——覆盖全谱系衍生品定价理论与数值方法。",
      accent: "#c08cff",
      modules: [
        { id: "L3-M1", cn: "期权定价基础", en: "Options Pricing Foundations", isNew: false, terms: [
          ["Black-Scholes-Merton 模型", "Black-Scholes-Merton Model", "欧式期权定价的经典封闭解模型"],
          ["二叉树模型", "Binomial Tree Model", "Cox-Ross-Rubinstein"],
          ["风险中性定价", "Risk-Neutral Pricing", "在风险中性测度下按无风险利率贴现定价"],
          ["期权 Greeks", "Option Greeks", "Delta / Gamma / Vega / Theta / Rho"],
          ["隐含波动率", "Implied Volatility", "由期权市价反推出的波动率"],
          ["波动率微笑", "Volatility Smile", "隐含波动率随行权价呈微笑状的现象"],
          ["波动率曲面", "Volatility Surface", "隐含波动率随行权价与到期的三维曲面"],
          ["局部波动率模型", "Local Volatility Model", "Dupire"],
          ["随机波动率模型", "Stochastic Volatility Model", "Heston / SABR"],
          ["粗糙波动率模型", "Rough Volatility Model", "Gatheral rBergomi"],
          ["跳扩散模型", "Jump-Diffusion Model", "Merton / Kou"],
          ["美式期权定价", "American Option Pricing", "Longstaff-Schwartz"],
          ["亚式期权", "Asian Option", "路径依赖"],
          ["障碍期权", "Barrier Option", "敲入 / 敲出"],
          ["回望期权", "Lookback Option", "收益取决于期间最高或最低价的期权"],
        ]},
        { id: "L3-M2", cn: "固定收益衍生品", en: "Fixed Income Derivatives", isNew: false, terms: [
          ["利率互换", "Interest Rate Swap (IRS)", "固定与浮动利率现金流互换"],
          ["基差互换", "Basis Swap", "两种浮动利率基准之间的互换"],
          ["利率上限 / 下限", "Cap / Floor", "为浮动利率设上限或下限的期权组合"],
          ["互换期权", "Swaption", "进入某利率互换的期权"],
          ["远期利率协议", "Forward Rate Agreement (FRA)", "锁定未来某期利率的远期协议"],
          ["收益率曲线构建", "Yield Curve Construction", "Bootstrap / Spline"],
          ["OIS 贴现", "OIS Discounting", "后 LIBOR 时代"],
          ["SOFR 转换", "SOFR Transition", "从 LIBOR 转向 SOFR 基准利率的改革"],
          ["多曲线框架", "Multi-Curve Framework", "贴现与远期用不同曲线的定价框架"],
          ["HJM 框架", "Heath-Jarrow-Morton Framework", "直接建模远期利率曲线演化的框架"],
          ["LMM / BGM 模型", "LIBOR Market Model", "Brace-Gatarek-Musiela"],
          ["Vasicek 模型", "Vasicek Model", "均值回复的单因子短期利率模型"],
          ["Hull-White 模型", "Hull-White Model", "可拟合初始利率曲线的短率模型"],
          ["凸性调整", "Convexity Adjustment", "对远期与期货利率差异的凸性修正"],
        ]},
        { id: "L3-M3", cn: "信用衍生品", en: "Credit Derivatives", isNew: false, terms: [
          ["信用违约互换", "Credit Default Swap (CDS)", "对冲信用违约风险的保险型互换"],
          ["信用违约互换指数", "CDS Index", "CDX / iTraxx"],
          ["总收益互换", "Total Return Swap (TRS)", "交换资产总收益与融资成本的互换"],
          ["信用联结票据", "Credit-Linked Note (CLN)", "内嵌信用违约风险的票据"],
          ["违约概率", "Probability of Default (PD)", "借款人违约的概率"],
          ["违约损失率", "Loss Given Default (LGD)", "违约后无法收回的损失比例"],
          ["违约暴露", "Exposure at Default (EAD)", "违约时刻的风险暴露金额"],
          ["信用估值调整", "Credit Valuation Adjustment (CVA)", "对手方违约风险对衍生品估值的扣减"],
          ["债务估值调整", "Debit Valuation Adjustment (DVA)", "自身违约风险带来的估值调整"],
          ["融资估值调整", "Funding Valuation Adjustment (FVA)", "无抵押头寸融资成本的估值调整"],
          ["资本估值调整", "Capital Valuation Adjustment (KVA)", "持有监管资本成本的估值调整"],
          ["保证金估值调整", "Margin Valuation Adjustment (MVA)", "初始保证金融资成本的估值调整"],
          ["XVA 框架", "XVA Framework", "全面估值调整"],
          ["结构化信用模型", "Structural Credit Model", "Merton"],
          ["简约信用模型", "Reduced-Form Credit Model", "Jarrow-Turnbull / Duffie-Singleton"],
        ]},
        { id: "L3-M4", cn: "波动率交易与异域衍生品", en: "Volatility Trading & Exotic Derivatives", isNew: false, terms: [
          ["方差互换", "Variance Swap", "直接交易已实现方差的合约"],
          ["波动率互换", "Volatility Swap", "直接交易已实现波动率的合约"],
          ["VIX 期货与期权", "VIX Futures & Options", "基于 VIX 波动率指数的期货与期权"],
          ["相关性互换", "Correlation Swap", "交易资产间已实现相关性的合约"],
          ["分散度交易", "Dispersion Trading", "做多个股波动、做空指数波动的相关性策略"],
          ["波动率曲面动态", "Vol Surface Dynamics", "Sticky Strike / Sticky Delta"],
          ["彩虹期权", "Rainbow Option", "收益取决于多资产表现的期权"],
          ["量化期权", "Quanto Option", "标的与结算货币不同、汇率固定的期权"],
          ["复合期权", "Compound Option", "以另一期权为标的的期权"],
          ["梯子期权", "Ladder Option", "达到预设价格档即锁定收益的期权"],
          ["气候衍生品", "Weather Derivatives", "HDD / CDD / CAT"],
          ["碳排放期权", "Carbon Emission Options", "EU ETS"],
        ]},
        { id: "L3-M5", cn: "数值方法与模型校准", en: "Numerical Methods & Model Calibration", isNew: false, terms: [
          ["蒙特卡洛模拟", "Monte Carlo Simulation", "用大量随机路径模拟定价复杂衍生品"],
          ["方差缩减技术", "Variance Reduction Techniques", "对偶变量 / 控制变量"],
          ["最小二乘蒙特卡洛", "Least Squares Monte Carlo (LSM)", "用回归估计续持价值来定价美式期权"],
          ["PDE 有限差分", "PDE Finite Difference", "显式 / 隐式 / Crank-Nicolson"],
          ["快速傅里叶变换定价", "FFT Pricing", "Carr-Madan"],
          ["模型校准", "Model Calibration", "最小化隐含波动率误差"],
          ["模型风险", "Model Risk", "模型假设错误或误用带来的风险"],
          ["参数估计", "Parameter Estimation", "从数据估计模型参数"],
          ["场景生成", "Scenario Generation", "生成用于定价与风控的情景路径"],
        ]},
      ],
    },

    /* ============== L4 ============== */
    {
      id: "L4", icon: "🛡️", cn: "组合与风险管理", en: "Portfolio & Risk Management",
      tag: "从 Markowitz 到气候 VaR——资产配置、因子投资、风险度量与绩效归因的全面框架。",
      accent: "#ff8f7a",
      modules: [
        { id: "L4-M1", cn: "现代组合理论", en: "Modern Portfolio Theory", isNew: false, terms: [
          ["均值-方差优化", "Mean-Variance Optimization", "Markowitz"],
          ["有效前沿", "Efficient Frontier", "给定风险下收益最优的组合集合"],
          ["资本资产定价模型", "Capital Asset Pricing Model (CAPM)", "用 Beta 解释预期收益的均衡模型"],
          ["套利定价理论", "Arbitrage Pricing Theory (APT)", "用多个因子解释收益的无套利模型"],
          ["Black-Litterman 模型", "Black-Litterman Model", "把市场均衡与主观观点结合的配置模型"],
          ["风险平价", "Risk Parity", "让各资产风险贡献相等的配置法"],
          ["最大分散化组合", "Maximum Diversification Portfolio", "最大化分散化比率的组合"],
          ["最小方差组合", "Minimum Variance Portfolio", "全局方差最小的组合"],
          ["等风险贡献", "Equal Risk Contribution (ERC)", "各成分风险贡献相等的组合"],
          ["因子投资", "Factor Investing", "Fama-French / Carhart"],
          ["智能 Beta", "Smart Beta", "按因子规则加权的指数化策略"],
          ["风险预算", "Risk Budgeting", "按风险额度而非资金分配的框架"],
        ]},
        { id: "L4-M2", cn: "风险度量与管理", en: "Risk Measurement & Management", isNew: false, terms: [
          ["在险价值", "Value at Risk (VaR)", "历史 / 参数 / 蒙特卡洛"],
          ["条件在险价值", "Conditional VaR (CVaR/ES)", "Expected Shortfall"],
          ["流动性调整 VaR", "Liquidity-Adjusted VaR (LVaR)", "计入平仓流动性成本的 VaR"],
          ["边际 VaR", "Marginal VaR", "某头寸变动对组合 VaR 的边际影响"],
          ["增量 VaR", "Incremental VaR", "增减某头寸引起的 VaR 变化"],
          ["成分 VaR", "Component VaR", "组合 VaR 在各头寸上的分解"],
          ["压力测试", "Stress Testing", "在极端情景下评估损失的测试"],
          ["情景分析", "Scenario Analysis", "设定情景评估组合表现的分析"],
          ["回测检验", "Backtesting", "Kupiec / Christoffersen"],
          ["风险因子映射", "Risk Factor Mapping", "把头寸映射到共同风险因子"],
          ["极端损失建模", "Extreme Loss Modeling", "EVT 应用"],
          ["系统性风险度量", "Systemic Risk Measures", "CoVaR / MES / SRISK"],
          ["尾部风险平价", "Tail Risk Parity", "尾部风险预算配置 · 从极端中获利"],
        ]},
        { id: "L4-M3", cn: "因子模型与 Alpha 研究", en: "Factor Models & Alpha Research", isNew: false, terms: [
          ["Fama-French 三 / 五因子", "Fama-French 3/5 Factor Model", "用规模、价值等因子解释收益的模型"],
          ["Carhart 四因子", "Carhart 4-Factor Model", "动量因子"],
          ["基本面因子", "Fundamental Factors", "价值 / 质量 / 成长"],
          ["技术因子", "Technical Factors", "动量 / 反转 / 波动率"],
          ["另类因子", "Alternative Factors", "情绪 / ESG / 季节性"],
          ["因子拥挤度", "Factor Crowding", "同一因子被过度拥挤交易的程度"],
          ["因子择时", "Factor Timing", "择时切换因子暴露的策略"],
          ["因子衰减分析", "Alpha Decay Analysis", "分析 Alpha 信号随时间衰减"],
          ["ML 因子发现", "ML Factor Discovery", "因子动物园问题"],
          ["因子组合构建", "Factor Portfolio Construction", "按目标因子暴露构建组合"],
          ["多因子风险模型", "Multi-Factor Risk Model", "Barra / Axioma"],
        ]},
        { id: "L4-M4", cn: "绩效归因与度量", en: "Performance Attribution & Measurement", isNew: false, terms: [
          ["Brinson 归因", "Brinson Attribution", "资产配置 / 选股效应"],
          ["风险归因", "Risk Attribution", "把组合风险分解到各来源"],
          ["持仓归因对交易归因", "Holdings vs Transaction Attribution", "持仓法与交易法两种归因口径"],
          ["信息比率", "Information Ratio", "超额收益与跟踪误差之比"],
          ["夏普比率", "Sharpe Ratio", "单位总风险的超额收益"],
          ["索提诺比率", "Sortino Ratio", "只惩罚下行波动的风险调整收益"],
          ["最大回撤", "Maximum Drawdown", "从峰值到谷底的最大跌幅"],
          ["Calmar 比率", "Calmar Ratio", "年化收益与最大回撤之比"],
          ["跟踪误差", "Tracking Error", "组合相对基准收益的波动"],
          ["GIPS 标准", "Global Investment Performance Standards", "全球统一的业绩披露标准（GIPS）"],
        ]},
        { id: "L4-M5", cn: "气候风险组合整合", en: "Climate Risk Portfolio Integration", isNew: true, terms: [
          ["碳 VaR", "Carbon VaR", "碳价格变动对组合的影响"],
          ["转型风险情景", "Transition Risk Scenarios", "有序 / 无序 / 热室"],
          ["物理风险量化", "Physical Risk Quantification", "量化气候物理灾害对资产的风险"],
          ["搁浅资产", "Stranded Assets", "因低碳转型而提前贬值的资产"],
          ["绿色资产比率", "Green Asset Ratio (GAR)", "绿色合规资产占比的监管指标"],
          ["组合碳足迹", "Portfolio Carbon Footprint", "WACI"],
          ["气候情景压力测试", "Climate Scenario Stress Test", "NGFS 情景"],
          ["净零路径", "Net Zero Pathway", "实现净零排放的减排路径"],
        ]},
      ],
    },

    /* ============== L5 ============== */
    {
      id: "L5", icon: "🧩", cn: "另类与结构化", en: "Alternative & Structured Products",
      tag: "从 CLO 到私募信贷——另类投资、结构化产品与大宗商品的完整知识图谱。",
      accent: "#f3c969",
      modules: [
        { id: "L5-M1", cn: "结构化信用产品", en: "Structured Credit Products", isNew: false, terms: [
          ["担保债务凭证", "Collateralized Debt Obligation (CDO)", "把债务资产打包分层出售的结构化产品"],
          ["合成 CDO", "Synthetic CDO", "用 CDS 而非实体资产构建的 CDO"],
          ["CDO 平方", "CDO-Squared", "以 CDO 分层为标的再打包的 CDO"],
          ["担保贷款凭证", "Collateralized Loan Obligation (CLO)", "以杠杆贷款为底层资产的分层证券"],
          ["CLO 权益层再定价", "CLO Equity Tranche Repricing", "CLO 权益层随利差与违约重新定价"],
          ["仓库融资", "Warehouse Financing", "CLO 建仓前融资"],
          ["资产支持证券", "Asset-Backed Securities (ABS)", "以各类应收或贷款为底层的资产支持证券"],
          ["住房抵押贷款证券", "Mortgage-Backed Securities (MBS)", "以住房抵押贷款为底层的证券"],
          ["商业抵押贷款证券", "Commercial MBS (CMBS)", "以商业地产抵押贷款为底层的证券"],
          ["分层结构", "Tranching", "优先级 / 夹层 / 权益"],
          ["信用增强", "Credit Enhancement", "超额抵押 / 次级化"],
          ["瀑布支付结构", "Waterfall Payment Structure", "按优先级层层分配现金流的结构"],
          ["违约相关性建模", "Default Correlation Modeling", "Gaussian Copula"],
          ["基础相关性", "Base Correlation", "CDO 分层定价所用的违约相关性"],
          ["损失分布", "Loss Distribution", "组合潜在损失的概率分布"],
        ]},
        { id: "L5-M2", cn: "私募股权与风险投资", en: "Private Equity & Venture Capital", isNew: false, terms: [
          ["杠杆收购", "Leveraged Buyout (LBO)", "用大量债务收购企业的交易"],
          ["管理层收购", "Management Buyout (MBO)", "管理层主导收购本公司"],
          ["内部收益率", "Internal Rate of Return (IRR)", "使净现值为零的年化收益率"],
          ["投入资本倍数", "Multiple on Invested Capital (MOIC)", "回笼资金相对投入本金的倍数"],
          ["J 曲线效应", "J-Curve Effect", "基金早期费用致收益先负后正的曲线"],
          ["干火药", "Dry Powder", "未调用资本"],
          ["资本催缴", "Capital Call / Drawdown", "LP 按需缴付承诺出资"],
          ["分配瀑布", "Distribution Waterfall", "GP 与 LP 之间收益分配的先后顺序"],
          ["优先回报", "Preferred Return / Hurdle Rate", "LP 优先获得的最低回报门槛"],
          ["GP / LP 结构", "GP/LP Structure", "普通合伙人管理、有限合伙人出资的架构"],
          ["附带权益", "Carried Interest", "GP 分享超额收益的业绩报酬"],
          ["管理费", "Management Fee", "按承诺或在管规模收取的管理费"],
          ["共同投资", "Co-Investment", "LP 在基金外与 GP 共同直投"],
          ["退出策略", "Exit Strategy", "IPO / 并购 / 二级市场"],
          ["二级市场交易", "Secondary Market Transaction", "转让已有基金份额的二级交易"],
        ]},
        { id: "L5-M3", cn: "对冲基金策略", en: "Hedge Fund Strategies", isNew: false, terms: [
          ["全球宏观", "Global Macro", "押注宏观趋势的对冲基金策略"],
          ["多空股票", "Long/Short Equity", "同时做多与做空股票的策略"],
          ["事件驱动", "Event-Driven", "并购套利 / 特殊情况"],
          ["相对价值", "Relative Value", "捕捉相关资产错价的策略"],
          ["可转债套利", "Convertible Arbitrage", "做多可转债、对冲其股票的套利"],
          ["固收套利", "Fixed Income Arbitrage", "捕捉固收产品间小幅错价的套利"],
          ["CTA / 管理期货", "CTA / Managed Futures", "系统化交易期货的趋势跟踪策略"],
          ["市场中性", "Market Neutral", "剥离市场 Beta、只赚 Alpha 的策略"],
          ["困境债务", "Distressed Debt", "投资陷入困境企业债务的策略"],
          ["量化策略", "Quantitative Strategies", "用模型与数据驱动的量化策略"],
          ["多策略基金", "Multi-Strategy Fund", "同时运行多种策略的基金"],
          ["风险套利", "Risk Arbitrage / Merger Arb", "押注并购成败的价差套利"],
        ]},
        { id: "L5-M4", cn: "私募信贷", en: "Private Credit", isNew: true, terms: [
          ["直接贷款", "Direct Lending", "绕过银行的私募贷款"],
          ["统一档贷款", "Unitranche", "优先 + 夹层合并为单一工具"],
          ["NAV 贷款", "NAV Lending", "基金净资产抵押融资"],
          ["夹层融资", "Mezzanine Financing", "介于债与股之间的夹层资本"],
          ["优先级担保贷款", "Senior Secured Loan", "有抵押、受偿顺序最优先的贷款"],
          ["第二留置权", "Second Lien", "抵押品受偿次于第一留置权的债务"],
          ["实物支付利息", "Payment-in-Kind (PIK) Interest", "以增加本金代替现金支付的利息"],
          ["契约条款", "Covenant Package", "Covenant-Lite 趋势"],
          ["赞助商支持贷款", "Sponsor-Backed Lending", "向 PE 收购标的提供的贷款"],
          ["资产基础贷款", "Asset-Based Lending (ABL)", "以应收、存货等资产作担保的贷款"],
          ["私募信贷基金结构", "Private Credit Fund Structure", "私募信贷基金的组织与放贷架构"],
          ["信贷基金杠杆", "Credit Fund Leverage", "订阅信贷 / 仓库融资"],
          ["私募信贷估值", "Private Credit Valuation", "公允价值 / 标记挑战"],
          ["流动性条款", "Liquidity Terms", "锁定期 / 赎回门槛"],
        ]},
        { id: "L5-M5", cn: "大宗商品", en: "Commodities", isNew: true, terms: [
          ["期限结构", "Term Structure", "Contango vs Backwardation"],
          ["便利收益率", "Convenience Yield", "持有现货相对期货的隐性便利收益"],
          ["持仓成本模型", "Cost of Carry Model", "用持有成本解释期现价差的模型"],
          ["滚动收益", "Roll Yield", "期货合约展期产生的收益或损耗"],
          ["裂解价差", "Crack Spread", "炼油利润价差"],
          ["火花价差", "Spark Spread", "发电利润价差"],
          ["压榨价差", "Crush Spread", "大豆加工价差"],
          ["碳排放权交易", "Carbon Emission Trading", "EU ETS / 碳配额"],
          ["碳信用", "Carbon Credit", "自愿市场 / 合规市场"],
          ["贵金属租赁利率", "Precious Metal Lease Rate", "贵金属借贷的租赁利率"],
          ["LME 仓库机制", "LME Warehouse Mechanism", "伦敦金属交易所的仓储交割机制"],
          ["商品指数", "Commodity Index", "S&P GSCI / BCOM"],
          ["实物交割对现金结算", "Physical vs Cash Settlement", "实物交割与现金结算两种方式"],
          ["基差风险", "Basis Risk", "现货与对冲工具价格不完全同步的风险"],
          ["天气衍生品定价", "Weather Derivatives Pricing", "HDD / CDD"],
          ["能源互换", "Energy Swap", "交换能源价格现金流的互换"],
          ["商品结构化票据", "Commodity Structured Note", "挂钩商品价格的结构化票据"],
        ]},
        { id: "L5-M6", cn: "另类数据与投资", en: "Alternative Data & Investment", isNew: false, terms: [
          ["卫星图像分析", "Satellite Imagery Analysis", "用卫星影像推断经济活动的另类数据"],
          ["信用卡交易数据", "Credit Card Transaction Data", "用刷卡数据预判消费与营收"],
          ["网络爬虫数据", "Web Scraping Data", "抓取网页信息构建投资信号"],
          ["社交媒体情绪", "Social Media Sentiment", "从社媒文本提取情绪信号"],
          ["供应链数据", "Supply Chain Data", "用供应链信息预判企业景气"],
          ["专利数据分析", "Patent Data Analysis", "用专利数据评估创新与竞争力"],
          ["地理位置数据", "Geolocation Data", "用位置数据推断客流与需求"],
          ["另类数据合规", "Alternative Data Compliance", "另类数据使用中的隐私与合规"],
        ]},
      ],
    },

    /* ============== L6 ============== */
    {
      id: "L6", icon: "🌍", cn: "宏观与行为", en: "Macro & Behavioral",
      tag: "从 Eurodollar 体系到行为偏差——理解驱动市场的宏观力量与人类认知局限。",
      accent: "#7ed0ff",
      modules: [
        { id: "L6-M1", cn: "宏观经济框架", en: "Macroeconomic Framework", isNew: false, terms: [
          ["IS-LM 模型", "IS-LM Model", "商品与货币市场共同决定利率与产出的模型"],
          ["菲利普斯曲线", "Phillips Curve", "通胀与失业此消彼长的关系曲线"],
          ["泰勒规则", "Taylor Rule", "按通胀与产出缺口设定政策利率的规则"],
          ["自然利率", "Natural Rate of Interest (R*)", "不刺激也不紧缩的均衡实际利率"],
          ["产出缺口", "Output Gap", "实际产出与潜在产出之差"],
          ["货币乘数", "Money Multiplier", "基础货币扩张为广义货币的倍数"],
          ["费雪方程", "Fisher Equation", "名义利率约等于实际利率加通胀"],
          ["购买力平价", "Purchasing Power Parity (PPP)", "汇率应使各国同质商品价格相等"],
          ["利率平价", "Interest Rate Parity", "覆盖 / 非覆盖"],
          ["三元悖论", "Impossible Trinity", "汇率稳定、资本自由、货币独立不可兼得"],
          ["财政乘数", "Fiscal Multiplier", "财政支出对产出的放大效应"],
          ["李嘉图等价", "Ricardian Equivalence", "债务融资与征税对消费影响等价的假说"],
        ]},
        { id: "L6-M2", cn: "全球流动性管道", en: "Global Liquidity Plumbing", isNew: true, terms: [
          ["离岸美元体系", "Eurodollar System", "Pozsar 框架"],
          ["央行互换额度", "Central Bank Swap Lines", "央行间互换本币以提供外币流动性"],
          ["准备金传导路径", "Reserve Transmission Channel", "QE / QT 的银行体系影响"],
          ["超额准备金", "Excess Reserves", "银行超过法定要求的准备金"],
          ["隔夜逆回购便利", "Overnight Reverse Repo Facility (ON RRP)", "美联储回收流动性、设利率下限的工具"],
          ["常备回购便利", "Standing Repo Facility (SRF)", "美联储按需提供回购、设利率上限的工具"],
          ["国债一般担保利率", "Treasury General Collateral Rate", "以国债为担保的一般回购利率"],
          ["抵押品速度", "Collateral Velocity", "抵押品复用速率"],
          ["影子银行信用创造", "Shadow Banking Credit Creation", "非银体系创造信用的机制"],
          ["全球美元融资缺口", "Global Dollar Funding Gap", "离岸机构美元资产与负债的缺口"],
          ["TGA 余额效应", "Treasury General Account (TGA) Effect", "财政部账户余额变动对银行准备金的影响"],
          ["准备金稀缺对充裕", "Reserve Scarcity vs Abundance", "银行准备金稀缺与充裕两种状态"],
          ["财政主导", "Fiscal Dominance", "财政政策压倒货币政策"],
          ["货币主导", "Monetary Dominance", "货币政策相对财政政策的主导地位"],
          ["央行资产负债表", "Central Bank Balance Sheet", "资产端 / 负债端分析"],
        ]},
        { id: "L6-M3", cn: "系统性危机机制", en: "Systemic Crisis Mechanics", isNew: false, terms: [
          ["明斯基时刻", "Minsky Moment", "债务累积后突然崩塌的时刻"],
          ["流动性螺旋", "Liquidity Spiral", "Brunnermeier-Pedersen"],
          ["保证金螺旋", "Margin Spiral", "追加保证金引发抛售的恶性循环"],
          ["抵押品火灾甩卖", "Collateral Fire Sale", "被迫低价抛售抵押品的连锁反应"],
          ["银行挤兑", "Bank Run", "Diamond-Dybvig"],
          ["传染效应", "Contagion Effect", "风险从一处向全市场蔓延"],
          ["太大而不能倒", "Too Big to Fail (TBTF)", "大机构倒闭危及全局、被迫救助"],
          ["系统重要性金融机构", "Systemically Important Financial Institution (SIFI)", "影响金融稳定的系统重要性机构"],
          ["宏观审慎政策", "Macroprudential Policy", "着眼系统性风险的宏观审慎监管"],
          ["逆周期资本缓冲", "Countercyclical Capital Buffer (CCyB)", "繁荣期计提、危机期释放的资本缓冲"],
          ["全球系统重要性银行", "Global Systemically Important Bank (G-SIB)", "全球系统重要性银行"],
          ["恢复与处置计划", "Recovery & Resolution Plan", "Living Will"],
          ["总损失吸收能力", "Total Loss-Absorbing Capacity (TLAC / MREL)", "处置时可吸收损失的资本与债务总量"],
        ]},
        { id: "L6-M4", cn: "行为金融学", en: "Behavioral Finance", isNew: false, terms: [
          ["前景理论", "Prospect Theory", "Kahneman-Tversky"],
          ["损失厌恶", "Loss Aversion", "对损失的痛感强于同等收益的快感"],
          ["心理账户", "Mental Accounting", "把钱按来源用途分门别类的心理"],
          ["锚定效应", "Anchoring Effect", "判断被初始参照值锚定的偏差"],
          ["确认偏差", "Confirmation Bias", "偏向接受支持己见证据的偏差"],
          ["过度自信", "Overconfidence", "高估自身判断准确度的倾向"],
          ["羊群效应", "Herding Behavior", "盲目跟随群体行动的羊群心理"],
          ["处置效应", "Disposition Effect", "过早卖盈、死扛亏损的处置倾向"],
          ["注意力偏差", "Attention Bias", "只关注吸睛信息的注意力偏差"],
          ["代表性偏差", "Representativeness Bias", "以典型印象代替概率判断的偏差"],
          ["可得性偏差", "Availability Bias", "高估易想起事件概率的偏差"],
          ["后见之明偏差", "Hindsight Bias", "事后觉得早该料到的偏差"],
          ["框架效应", "Framing Effect", "同一信息表述方式改变决策的效应"],
          ["禀赋效应", "Endowment Effect", "拥有某物后高估其价值的倾向"],
        ]},
        { id: "L6-M5", cn: "叙事与认知动力学", en: "Narrative & Cognitive Dynamics", isNew: false, terms: [
          ["叙事经济学", "Narrative Economics", "Shiller"],
          ["反身性理论", "Reflexivity Theory", "Soros"],
          ["凯恩斯选美比赛", "Keynesian Beauty Contest", "猜别人怎么想而非基本面的博弈"],
          ["市场叙事周期", "Market Narrative Cycle", "市场故事从形成到破灭的周期"],
          ["信号对噪音崩溃", "Signal vs Noise Collapse", "信号可信度阈值"],
          ["宏观叙事覆写", "Macro Narrative Overwriting", "信念重塑过程"],
          ["共识对市场现实", "Consensus vs Market Reality", "一致预期与真实走势的落差"],
          ["信念驱动定价", "Belief-Driven Pricing", "信念自我实现"],
          ["注意力经济", "Attention Economy", "金融市场中的注意力分配"],
          ["制度盲点", "Regime Blind Spot", "对体制 / 范式转变的系统性失明"],
        ]},
        { id: "L6-M6", cn: "新兴市场与主权风险", en: "Emerging Markets & Sovereign Risk", isNew: false, terms: [
          ["资本管制", "Capital Controls as Macro Tool", "用资本管制作为宏观调控工具"],
          ["原罪假说", "Original Sin Redux", "本币 / 外币债务结构"],
          ["荷兰病", "Dutch Disease Mechanism", "资源出口推高汇率、挤压制造业"],
          ["突然停止", "Sudden Stop Dynamics", "外资骤然撤离引发的危机动态"],
          ["浮动恐惧", "Fear of Floating", "新兴市场不敢让汇率自由浮动"],
          ["主权 CDS", "Sovereign CDS", "对冲主权违约风险的信用互换"],
          ["在岸对离岸债务墙", "China Onshore/Offshore Debt Wall", "在岸与离岸债市间的分割壁垒"],
          ["准主权溢价", "Quasi-Sovereign Premium", "准主权发行体相对主权的利差溢价"],
          ["资本管制渗透定价", "Capital Control Seepage Pricing", "资本管制下资金渗漏的定价"],
          ["EM 本币债外资持仓阈值", "EM Local Bond Foreign Holding Threshold", "外资持有 EM 本币债的临界比例"],
          ["MDB 混合融资", "MDB Blended Finance", "多边开发银行风险分担"],
          ["巴黎俱乐部机制", "Paris Club Mechanism", "主权债务重组"],
          ["集体行动条款", "Collective Action Clauses (CACs)", "债务重组中多数决约束少数的条款"],
          ["债务可持续分析", "Debt Sustainability Analysis (DSA)", "IMF 框架"],
        ]},
        { id: "L6-M7", cn: "地缘政治风险量化", en: "Geopolitical Risk Quantification", isNew: true, terms: [
          ["地缘政治风险指数", "Geopolitical Risk Index (GPR)", "Caldara-Iacoviello"],
          ["制裁经济学", "Sanctions Economics", "经济制裁的机制与市场影响"],
          ["供应链脱钩风险", "Supply Chain Decoupling Risk", "供应链脱钩带来的风险"],
          ["能源安全溢价", "Energy Security Premium", "能源供给安全带来的价格溢价"],
          ["技术封锁风险", "Technology Blockade Risk", "半导体 / AI"],
          ["地缘 Beta", "Geopolitical Beta", "资产对地缘事件的敏感度"],
          ["冲突概率建模", "Conflict Probability Modeling", "量化地缘冲突发生概率"],
          ["友岸外包", "Friend-Shoring", "向盟友国家转移供应链"],
        ]},
      ],
    },

    /* ============== L7 ============== */
    {
      id: "L7", icon: "🔬", cn: "专业纵深", en: "Specialized Verticals",
      tag: "保险精算、贸易融资、ESG、房地产、主权债务、量化架构与金融科技——垂直领域的专业深度。",
      accent: "#9d8cff",
      modules: [
        { id: "L7-M1", cn: "保险与精算金融", en: "Insurance & Actuarial Finance", isNew: false, terms: [
          ["偿付能力监管", "Solvency II · IFRS 17 · SCR", "欧洲保险业偿付能力与会计监管框架"],
          ["长寿互换定价", "Longevity Swap Pricing", "精算表对市场定价的套利窗口"],
          ["偿二代 SCR 资本优化", "Solvency II SCR Capital Optimization", "优化偿二代所需资本的策略"],
          ["再保险边车结构", "Reinsurance Sidecar Structure", "引入外部资本分担再保险风险的载体"],
          ["巨灾债券触发比较", "Cat Bond Trigger Comparison", "赔偿型 / 参数型 / 行业损失型"],
          ["IFRS 17 合同服务利润释放", "IFRS 17 CSM Release", "保险合同服务利润按期确认释放"],
          ["再保险定价周期", "Reinsurance Pricing Cycle", "Combined Ratio"],
          ["精算贴现率假设", "Actuarial Discount Rate Assumption", "利率对 DBO 的放大"],
          ["触发型去风险滑道", "Trigger Glide Path (De-risking)", "养老金按触发条件逐步降风险的路径"],
          ["PBGC 可变费率保费", "PBGC Variable Rate Premium", "美国养老金担保机构按缺口收取的保费"],
          ["盈余对冲策略", "Surplus Hedge Strategy", "对冲资产负债盈余波动的策略"],
          ["寿险久期缺口螺旋", "Life Insurance Duration Gap Spiral", "寿险资负久期错配放大的风险"],
          ["未决赔款准备金偏差", "IBNR Reserve Development Bias", "已发生未报案赔款准备金的估计偏差"],
        ]},
        { id: "L7-M2", cn: "贸易融资与司库金融", en: "Trade & Treasury Finance", isNew: false, terms: [
          ["真实出售意见", "True Sale Opinion", "应收款证券化的法律效力判定"],
          ["应收账款证券化", "Receivables Securitization", "把应收账款打包成证券融资"],
          ["反向保理", "Reverse Factoring (Payables SCF)", "由核心企业发起的应付账款供应链融资"],
          ["动态贴现对供应链金融", "Dynamic Discounting vs SCF", "动态提前付款折扣与供应链金融的比较"],
          ["福费廷（无追索权）", "Forfaiting (Without Recourse)", "无追索权买断出口应收票据"],
          ["信用证技术性拒付套利", "L/C Technical Discrepancy Arb", "利用信用证单据瑕疵拒付的套利"],
          ["供应链金融对银行 NSFR 影响", "SCF Impact on Bank NSFR", "供应链金融对银行稳定资金比率的影响"],
          ["贸易融资证券化", "TF-ABS (Trade Finance Securitization)", "把贸易融资资产证券化"],
          ["一带一路基础设施融资风险", "BRI Infrastructure Financing Risk", "一带一路基建融资的信用与政治风险"],
          ["供应链金融数字化平台", "SCF Digital Platforms", "供应链金融的数字化撮合平台"],
        ]},
        { id: "L7-M3", cn: "碳市场与 ESG 金融", en: "Carbon Market & ESG Finance", isNew: false, terms: [
          ["ETS 价格形成机制", "ETS Price Formation Mechanism", "碳排放交易体系的价格形成机制"],
          ["巴黎协定第六条 ITMO", "Paris Art.6 ITMO Fungibility", "国际碳信用可替换性"],
          ["碳边境调节机制", "Carbon Border Adjustment Mechanism (CBAM)", "欧盟对进口商品征收的碳边境税"],
          ["TNFD 生物多样性信用定价", "TNFD Biodiversity Credit Pricing", "生物多样性信用的定价框架"],
          ["TCFD 物理对转型风险", "TCFD Physical vs Transition Risk", "气候物理风险与转型风险的披露"],
          ["自愿碳市场标准竞争", "VCM Standards Competition", "Verra vs Gold Standard"],
          ["气候压力测试", "Climate Stress Test", "NGFS 情景"],
          ["绿色分类法分歧", "Green Taxonomy Divergence", "EU vs 中国"],
          ["可持续金融披露", "SFDR / EU Taxonomy", "欧盟可持续金融披露与分类标准"],
        ]},
        { id: "L7-M4", cn: "房地产金融", en: "Real Estate Finance", isNew: false, terms: [
          ["租赁权对永久产权", "Leasehold vs Fee Simple", "地面租约二分法"],
          ["PPP 可用性付款结构", "PPP Availability Payment Structure", "政府按项目可用性付费的 PPP 结构"],
          ["CMBS B 档经济学", "CMBS B-Piece Economics", "首亏档信息优势"],
          ["资本化率压缩套利", "Cap Rate Compression Arbitrage", "利用资本化率下行推升估值的套利"],
          ["DSCR 机制", "DSCR Mechanics", "债务覆盖率约束"],
          ["售后回租工程", "Sale-Leaseback Engineering", "出售资产再租回以释放现金的安排"],
          ["房地产 PE 分配瀑布", "RE PE Distribution Waterfall", "房地产私募基金的收益分配结构"],
          ["REIT 结构与税务", "REIT Structure & Tax", "房地产信托的组织形式与税务"],
        ]},
        { id: "L7-M5", cn: "主权债务与 EM 固收", en: "Sovereign Debt & EM Fixed Income", isNew: true, terms: [
          ["主权债务重组", "Sovereign Debt Restructuring", "主权国家债务的重组安排"],
          ["Brady 债券遗产", "Brady Bond Legacy", "上世纪拉美债务重组的 Brady 债券遗留"],
          ["EM 本币债投资", "EM Local Currency Bond Investing", "投资新兴市场本币计价债券"],
          ["EM 外币主权债", "EM Hard Currency Sovereign Debt", "新兴市场以硬通货发行的主权债"],
          ["主权评级方法论", "Sovereign Rating Methodology", "主权信用评级的方法论"],
          ["GDP 挂钩债券", "GDP-Linked Bond", "票息与经济增长挂钩的债券"],
          ["主权财富基金策略", "Sovereign Wealth Fund Strategy", "主权财富基金的投资策略"],
          ["外汇储备管理", "FX Reserve Management", "一国外汇储备的管理"],
          ["EM 公司债", "EM Corporate Bond", "新兴市场企业债"],
          ["前沿市场债务", "Frontier Market Debt", "前沿（更早期）市场的债务投资"],
          ["拍卖覆盖率（投标倍数）", "Bid-to-Cover Ratio", "一级 / 二级市场吸收力 · 拍卖需求强弱机制"],
        ]},
        { id: "L7-M6", cn: "量化交易系统架构", en: "Quantitative Trading System Architecture", isNew: true, terms: [
          ["策略回测框架", "Backtesting Framework", "避免前瞻 / 生存偏差"],
          ["Alpha 衰减分析", "Alpha Decay Analysis", "信号半衰期"],
          ["执行管理系统", "Execution Management System (EMS)", "面向交易执行与路由的系统"],
          ["订单管理系统", "Order Management System (OMS)", "管理订单全生命周期的系统"],
          ["风险实时监控", "Real-Time Risk Monitoring", "对头寸与风险的实时监控"],
          ["策略容量分析", "Strategy Capacity Analysis", "评估策略可承载的资金规模"],
          ["滑点模型", "Slippage Model", "预测下单滑点的模型"],
          ["延迟优化", "Latency Optimization", "降低交易系统延迟的优化"],
          ["数据清洗管道", "Data Cleaning Pipeline", "清洗与规整原始数据的流水线"],
          ["特征工程框架", "Feature Engineering Framework", "构造预测特征的工程框架"],
          ["模型衰退检测", "Model Decay Detection", "监测模型表现衰退"],
          ["组合构建引擎", "Portfolio Construction Engine", "由信号生成目标组合的引擎"],
        ]},
        { id: "L7-M7", cn: "金融科技与支付基础设施", en: "FinTech & Payment Infrastructure", isNew: true, terms: [
          ["FedNow 即时支付", "FedNow Instant Payment", "美联储的即时支付系统"],
          ["SWIFT gpi", "SWIFT gpi", "全球支付创新"],
          ["CBDC 架构", "CBDC Architecture", "零售 / 批发 CBDC"],
          ["稳定币机制", "Stablecoin Mechanism", "法币储备 / 算法"],
          ["嵌入式金融", "Embedded Finance", "把金融服务嵌入非金融场景"],
          ["开放银行", "Open Banking", "PSD2 / API 经济"],
          ["实时全额结算", "Real-Time Gross Settlement (RTGS)", "逐笔实时全额清算系统"],
          ["代币化资产", "Tokenized Assets", "证券 / 房地产代币化"],
          ["分布式账本技术", "Distributed Ledger Technology (DLT)", "分布式账本（区块链）技术"],
          ["监管科技", "RegTech", "合规自动化"],
        ]},
      ],
    },

    /* ============== L8 ============== */
    {
      id: "L8", icon: "⚖️", cn: "监管与合规架构", en: "Regulatory & Compliance",
      tag: "全新层级——从 Basel III/IV 到反洗钱，覆盖全球金融监管体系与合规科技。",
      accent: "#ff9ec7",
      modules: [
        { id: "L8-M1", cn: "银行业资本监管", en: "Banking Capital Regulation", isNew: false, terms: [
          ["Basel III/IV 终版", "Basel III/IV Endgame", "巴塞尔资本监管的最终落地版本"],
          ["风险加权资产", "Risk-Weighted Assets (RWA)", "按风险加权计算的资产，资本充足率分母"],
          ["最低资本要求", "Minimum Capital Requirements", "CET1 / AT1 / Tier 2"],
          ["杠杆比率", "Leverage Ratio", "资本与总敞口之比，不看风险权重"],
          ["流动性覆盖率", "Liquidity Coverage Ratio (LCR)", "覆盖 30 天压力流出的优质流动资产比率"],
          ["净稳定资金比率", "Net Stable Funding Ratio (NSFR)", "一年期稳定资金对所需资金的比率"],
          ["资本留存缓冲", "Capital Conservation Buffer", "平时计提、承压时可动用的资本缓冲"],
          ["逆周期缓冲", "Countercyclical Buffer", "随信贷周期调节的额外资本要求"],
          ["G-SIB 附加资本", "G-SIB Capital Surcharge", "全球系统重要性银行的附加资本"],
          ["标准法对内评法", "Standardised vs IRB Approach", "标准法与内部评级法两种资本计量"],
          ["操作风险标准化", "Operational Risk Standardised Approach", "操作风险的标准化资本计量"],
          ["交易账户基本审查", "Fundamental Review of the Trading Book (FRTB)", "交易账户市场风险资本的新规"],
          ["信用风险输出下限", "Credit Risk Output Floor", "72.5%"],
          ["大额风险暴露", "Large Exposure Framework", "限制对单一对手集中度的框架"],
        ]},
        { id: "L8-M2", cn: "市场行为与投资者保护", en: "Market Conduct & Investor Protection", isNew: false, terms: [
          ["Dodd-Frank 法案", "Dodd-Frank Act", "美国 2010 年金融改革法案"],
          ["Volcker 规则", "Volcker Rule", "自营交易限制"],
          ["MiFID II / MiFIR", "MiFID II / MiFIR", "欧盟金融工具市场监管指令"],
          ["Reg NMS", "Regulation NMS", "美国全国市场系统监管规则"],
          ["Reg ATS", "Regulation ATS", "美国对另类交易系统的监管"],
          ["最佳执行", "Best Execution", "为客户争取最优成交结果的义务"],
          ["交易报告义务", "Trade Reporting Obligations", "成交须及时上报的义务"],
          ["市场滥用条例", "Market Abuse Regulation (MAR)", "欧盟打击市场操纵与内幕的条例"],
          ["内幕交易监管", "Insider Trading Regulation", "禁止利用内幕信息交易的监管"],
          ["卖空限制", "Short Selling Restrictions", "对卖空的限制与披露要求"],
          ["算法交易监管", "Algorithmic Trading Regulation", "对算法与高频交易的监管"],
          ["适当性与适合性", "Appropriateness & Suitability", "产品与客户风险匹配的合规要求"],
        ]},
        { id: "L8-M3", cn: "衍生品与清算监管", en: "Derivatives & Clearing Regulation", isNew: false, terms: [
          ["EMIR", "European Market Infrastructure Regulation", "欧盟场外衍生品清算与报告监管（EMIR）"],
          ["中央清算义务", "Mandatory Central Clearing", "标准化衍生品须中央清算的要求"],
          ["非集中清算保证金规则", "Margin Rules for Non-Centrally Cleared Derivatives", "UMR"],
          ["交易存储库", "Trade Repository", "汇集衍生品交易数据的存储库"],
          ["衍生品报告", "Derivatives Reporting", "CFTC / ESMA"],
          ["互换交易商注册", "Swap Dealer Registration", "互换交易商的注册与合规义务"],
          ["头寸限制", "Position Limits", "对投机头寸规模的上限"],
          ["跨境衍生品监管", "Cross-Border Derivatives Regulation", "跨境衍生品的监管协调"],
          ["CCP 恢复与处置", "CCP Recovery & Resolution", "中央对手方危机时的恢复与处置"],
        ]},
        { id: "L8-M4", cn: "反洗钱与合规科技", en: "AML & Compliance Technology", isNew: false, terms: [
          ["了解你的客户", "Know Your Customer (KYC)", "核实客户身份的合规要求"],
          ["客户尽职调查", "Customer Due Diligence (CDD)", "对客户背景的尽职调查"],
          ["增强尽职调查", "Enhanced Due Diligence (EDD)", "对高风险客户的强化尽调"],
          ["可疑交易报告", "Suspicious Activity Report (SAR)", "向监管报送可疑交易"],
          ["反洗钱筛查", "AML Screening", "制裁名单 / PEP"],
          ["旅行规则", "Travel Rule", "FATF Rec.16"],
          ["受益所有权", "Beneficial Ownership", "最终实际控制或受益的自然人"],
          ["反洗钱机器学习", "AML Machine Learning", "异常检测"],
          ["FATCA / CRS", "FATCA / Common Reporting Standard", "跨境账户税务信息交换制度"],
          ["合规自动化", "Compliance Automation", "RegTech 应用"],
        ]},
        { id: "L8-M5", cn: "资产管理与基金监管", en: "Asset Management & Fund Regulation", isNew: false, terms: [
          ["投资公司法", "Investment Company Act", "40 Act"],
          ["投资顾问法", "Investment Advisers Act", "美国投资顾问监管法"],
          ["AIFMD", "Alternative Investment Fund Managers Directive", "欧盟另类投资基金经理指令（AIFMD）"],
          ["UCITS", "Undertakings for Collective Investment", "欧盟可跨境销售的公募基金框架（UCITS）"],
          ["私募基金监管", "Private Fund Regulation", "Form PF"],
          ["流动性风险管理", "Liquidity Risk Management", "SEC Rule 22e-4"],
          ["基金估值规则", "Fund Valuation Rules", "基金资产估值的规则"],
          ["业绩费规则", "Performance Fee Rules", "业绩报酬收取的规则"],
          ["ESG 披露要求", "ESG Disclosure Requirements", "SFDR"],
          ["跨境基金分销", "Cross-Border Fund Distribution", "基金跨境销售的合规"],
        ]},
      ],
    },
  ],
};

/* ---- 工具方法（供页面调用，勿改） ---- */
ARCH.findLayer = function (id) {
  return this.layers.find((l) => l.id === id) || null;
};
ARCH.moduleCount = function () {
  return this.layers.reduce((n, l) => n + l.modules.length, 0);
};
ARCH.termCount = function () {
  return this.layers.reduce(
    (n, l) => n + l.modules.reduce((m, mod) => m + mod.terms.length, 0), 0);
};
ARCH.layerTermCount = function (layer) {
  return layer.modules.reduce((m, mod) => m + mod.terms.length, 0);
};
/* 扁平化所有术语，附带所属层 / 模块，供全局搜索使用 */
ARCH.flatTerms = function () {
  const out = [];
  this.layers.forEach((l) =>
    l.modules.forEach((mod) =>
      mod.terms.forEach((t) =>
        out.push({ cn: t[0], en: t[1], note: t[2] || "", layer: l, module: mod }))));
  return out;
};

if (typeof window !== "undefined") window.ARCH = ARCH;
